pre-commit hook should try local dev env before Docker and skip TODO
Most devs are *not* on Docker, so try running everything locally first.
If it fails, then try running under Docker.

Also, skip the TODO - migrate away from using TODO and use GitHub Issues.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -2,53 +2,77 @@
 
 early_exit=0
 
-# Default to using sudo on Linux
-sudo=''
-if [ "$(uname)" = 'Linux' ]; then
-  sudo='sudo'
-  echo "Looks like you're on a Linux machine. Running all docker-compose commands with sudo..."
-fi
-
 # Only run if there are files staged for commit
 changed_files=$(git diff --cached --name-only --diff-filter=ACM | paste -s -d' ' -)
 if [ -n "$changed_files" ]; then
 
-  # rubocop
-  $sudo docker-compose run web rubocop $changed_files
-  if [ $? -ne 0 ]; then
-    >&2 echo "Rubocop check failed, try running: bundle exec rubocop --auto-correct $changed_files"
-    early_exit=$(($early_exit + 1))
+  # Run rubocop
+  echo "Running rubocop $changed_files (this may take a few seconds)"
+  if rubocop_results=$(rubocop $changed_files 2>&1); then
+    if $(echo $rubocop_results | grep -q "Offenses:" 2>&1); then
+      >&2 echo "\n** Rubocop found some code style it disagreed with, try autofixing by running **\n  rubocop --auto-correct $changed_files\n"
+    else
+      echo "rubocop ran successfully; moving on to the next pre-commit check"
+    fi
   else
-    >&1 echo "Rubocop check complete"
-  fi
-
-  # Run `rake notes` job
-  $sudo docker-compose run web rake notes > TODO
-  if [ $? -ne 0 ]; then
-    >&2 echo "rake notes > TODO: failed"
-    early_exit=$(($early_exit + 1))
-  else
-    git add TODO
-    >&1 echo "TODO notes added"
+    rubocop_docker_cmd="sudo docker-compose run web rubocop $changed_files"
+    echo "\nCannot run rubocop locally -- attempting to run under Docker\n  $rubocop_docker_cmd\n"
+    if rubocop_results=$($rubocop_docker_cmd 2>&1); then
+      echo "rubocop ran successfully in Docker; moving on to the next pre-commit check"
+    else
+      if $(echo $rubocop_results | grep -q "Offenses:" 2>&1); then
+        >&2 echo "\n** Rubocop found some code style it disagreed with, try autofixing by running **\n  sudo docker-compose run web rubocop --auto-correct $changed_files\n"
+      else
+        echo "Could not run rubocop. Please try running it manually and report the issue."
+      fi
+      early_exit=$(($early_exit + 1))
+    fi
   fi
 
   # Run 'annotate' gem (populates app/models, spec/ with schema changes)
-  annotate_results=$($sudo docker-compose run web annotate)
-  if [ -n "$annotate_results" ]; then
-    annotated_files=$(echo $annotate_results | awk -FAnnotated '{print $2}' | awk -F: '{print $2}' | sed s/,//g)
-    if [ -z "$annotated_files" ]; then
-      >&1 echo 'No files annotated'
+  echo "Running 'annotate' (almost done)"
+  if annotate_results=$(annotate); then
+    echo "annotate ran successfully"
+    if [ -n "$annotate_results" ]; then
+      annotated_files=$(echo $annotate_results | awk -FAnnotated '{print $2}' | awk -F: '{print $2}' | sed s/,//g)
+      if [ -z "$annotated_files" ]; then
+        >&1 echo 'No files annotated'
+      else
+        >&2 echo "\n\n** Files updated with annotate! please git-add them and commit again **"
+        >&2 echo "Run:\n  git add -p $annotated_files"
+        early_exit=$(($early_exit + 1))
+      fi
     else
-      >&2 echo "Files updated with annotate! please git-add them and commit again"
-      >&2 echo "Run:\n  git add -p $annotated_files"
+      >&1 echo 'No files annotated'
+    fi
+
+  else
+    annotate_cmd="sudo docker-compose run web annotate"
+    echo "Cannot run TODO rake task locally -- attempting to run under Docker\n  $annotate_cmd"
+    if annotate_results=$($annotate_cmd); then
+      if [ -n "$annotate_results" ]; then
+        annotated_files=$(echo $annotate_results | awk -FAnnotated '{print $2}' | awk -F: '{print $2}' | sed s/,//g)
+        if [ -z "$annotated_files" ]; then
+          >&1 echo 'No files annotated'
+        else
+          >&2 echo "\n\n** Files updated with annotate! please git-add them and commit again **"
+          >&2 echo "Run:\n  git add -p $annotated_files"
+          early_exit=$(($early_exit + 1))
+        fi
+      else
+        >&1 echo 'No files annotated'
+      fi
+    else
+      echo "Could not run annotate. Please try running it manually and report the issue."
       early_exit=$(($early_exit + 1))
     fi
-  else
-    >&1 echo 'No files annotated'
   fi
 
   if [ $early_exit -ne 0 ]; then
-    >&2 echo '** git-commit ABORTED - see above **'
+    >&2 echo "\n\n** git-commit ABORTED - see above **"
+    exit 1
+  else
+    echo "\n\ngit pre-commit hooks successful - commiting staged changes now"
     exit 1
   fi
 fi
